#!/bin/bash

case $1 in
  breaking*)
    ((MAJOR_VERSION=MAJOR_VERSION+1))
    MINOR_VERSION=0
    PATCH_VERSION=0
    ;;
  feature*)
    ((MINOR_VERSION=MINOR_VERSION+1))
    PATCH_VERSION=0
    ;;
  *)
    ((PATCH_VERSION=PATCH_VERSION+1))
esac

echo "${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"
