#!/usr/bin/env ruby

message=`head -n1 .git/COMMIT_EDITMSG`.gsub(/\n/, '')
regex = /^CORE-\d+/

if message !~ regex
  puts
  puts " \033[31m! Failed to commit !\e[0m"
  puts " Looks like you forgot to add the Jira ticket number to this commit message"
  puts
  puts " \033[33mEG: CORE-1092 #{message}\e[0m"
  exit 1
end
